name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main # Chạy workflow khi có thay đổi trên nhánh 'main'
  pull_request:
    branches:
      - main # Chạy workflow khi có pull request đến nhánh 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v2

      # Bước 2: Cài đặt Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Bước 3: Login vào Docker Hub (hoặc registry khác)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Bước 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t langhoangtien/lifetek-docs:${{ github.sha }} .

      # Bước 5: Push Docker image lên Docker Hub (hoặc registry khác)
      - name: Push Docker image
        run: |
          docker push langhoangtien/lifetek-docs:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v2

      # Bước 2: SSH vào server để deploy container
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull langhoangtien/lifetek-docs:${{ github.sha }}
            if [ $(docker ps -a -q -f name=lifetek-docs-container) ]; then
            # Nếu container tồn tại, dừng và xóa nó
              docker stop lifetek-docs-container
              docker rm lifetek-docs-container
            fi
            # Tạo container mới từ image vừa pull
            docker run -d -p 3001:3001 --name lifetek-docs-container langhoangtien/lifetek-docs:${{ github.sha }}
